import type { Regulation } from "./mock-data";

// Generated from Daftar_Peraturan_Perpajakan_Esensial_Indonesia_2026.xlsx.
// The original registry states these essential Indonesian tax regulations were verified on 20 July 2026.
// Source provenance is retained in content so the RAG bot can explain authority, status, and update needs.
export const essentialRegulationSeeds: Regulation[] = [
  {
    "id": "essential-01-uu-no-6-tahun-1983-tentang-kup",
    "topic": "general",
    "title": "UU No. 6 Tahun 1983 tentang KUP",
    "citation": "UU No. 6 Tahun 1983 tentang KUP",
    "focus": "Ketentuan umum dan tata cara perpajakan: pendaftaran, SPT, pembayaran, pemeriksaan, ketetapan, sanksi, keberatan, bukti permulaan, dan penyidikan.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Details/46986/uu-no-6-tahun-1983",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Fondasi prosedural untuk hampir seluruh pekerjaan compliance, advisory, pemeriksaan, dan sengketa..\\nVerified status as of 20 July 2026: Berlaku — gunakan naskah konsolidasi.\\nImportant relationship/amendment: Telah beberapa kali diubah, terutama oleh UU HPP dan UU Cipta Kerja..\\nEffective period / temporal relevance: Sejak 1 Januari 1984.\\nDatabase note: Simpan riwayat perubahan dan status per pasal..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-02-uu-no-7-tahun-1983-tentang-pajak-penghasilan",
    "topic": "transfer_pricing",
    "title": "UU No. 7 Tahun 1983 tentang Pajak Penghasilan",
    "citation": "UU No. 7 Tahun 1983 tentang Pajak Penghasilan",
    "focus": "Subjek, objek, biaya fiskal, tarif, pemotongan/pemungutan, BUT, hubungan istimewa, CFC, dan kredit pajak luar negeri.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Details/46988",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Dasar utama seluruh analisis PPh badan, orang pribadi, withholding tax, transfer pricing, dan pajak internasional..\\nVerified status as of 20 July 2026: Berlaku — gunakan naskah konsolidasi.\\nImportant relationship/amendment: Telah beberapa kali diubah, terutama oleh UU HPP dan UU Cipta Kerja..\\nEffective period / temporal relevance: Sejak 1 Januari 1984.\\nDatabase note: Versi tahun pajak harus dipetakan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-03-uu-no-8-tahun-1983-tentang-ppn-dan-ppnbm",
    "topic": "vat",
    "title": "UU No. 8 Tahun 1983 tentang PPN dan PPnBM",
    "citation": "UU No. 8 Tahun 1983 tentang PPN dan PPnBM",
    "focus": "Objek PPN, PKP, DPP, tarif, faktur pajak, pajak masukan, ekspor-impor, dan PPnBM.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Details/46990/uu-no-8-tahun-1983",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Dasar substantif untuk transaksi barang/jasa domestik maupun lintas negara..\\nVerified status as of 20 July 2026: Berlaku — gunakan naskah konsolidasi.\\nImportant relationship/amendment: Telah beberapa kali diubah, terutama oleh UU HPP..\\nEffective period / temporal relevance: Sejak 1 Juli 1984.\\nDatabase note: Periksa ketentuan transisi tarif dan DPP..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-04-uu-no-7-tahun-2021-tentang-harmonisasi-peraturan-perpajakan",
    "topic": "vat",
    "title": "UU No. 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan",
    "citation": "UU No. 7 Tahun 2021 tentang Harmonisasi Peraturan Perpajakan",
    "focus": "Mengubah rezim KUP, PPh, PPN, program pengungkapan sukarela, pajak karbon, dan cukai.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Details/185162/uu-no-7-tahun-2021",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Amending law utama; wajib dibaca bersama undang-undang induk..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mengubah UU KUP, UU PPh, UU PPN, dan undang-undang terkait..\\nEffective period / temporal relevance: 29 Oktober 2021; ketentuan efektif berbeda-beda.\\nDatabase note: Jangan diperlakukan sebagai pengganti penuh UU induk..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-05-uu-no-6-tahun-2023-tentang-cipta-kerja",
    "topic": "general",
    "title": "UU No. 6 Tahun 2023 tentang Cipta Kerja",
    "citation": "UU No. 6 Tahun 2023 tentang Cipta Kerja",
    "focus": "Menetapkan Perppu Cipta Kerja dan memuat perubahan lanjutan atas beberapa ketentuan perpajakan.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Details/246523/uu-no-6-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Diperlukan untuk membaca teks konsolidasi terbaru UU KUP dan UU PPh..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Memengaruhi ketentuan dalam UU KUP dan UU PPh..\\nEffective period / temporal relevance: 31 Maret 2023.\\nDatabase note: Gunakan bersama UU HPP dan UU induk..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-06-uu-no-19-tahun-1997-jo-uu-no-19-tahun-2000",
    "topic": "general",
    "title": "UU No. 19 Tahun 1997 jo. UU No. 19 Tahun 2000",
    "citation": "UU No. 19 Tahun 1997 jo. UU No. 19 Tahun 2000",
    "focus": "Penagihan pajak dengan Surat Paksa, penyitaan, pencegahan, penyanderaan, dan lelang.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Search?search=UU%2019%20Tahun%201997%20Penagihan%20Pajak%20Surat%20Paksa",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Dasar hukum penagihan aktif dan tindakan terhadap penanggung pajak..\\nVerified status as of 20 July 2026: Berlaku — gunakan naskah konsolidasi.\\nImportant relationship/amendment: UU No. 19 Tahun 2000 mengubah UU No. 19 Tahun 1997..\\nEffective period / temporal relevance: Sejak 1997; perubahan sejak 2000.\\nDatabase note: Hubungkan dengan PMK 61/2023..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-07-uu-no-14-tahun-2002-tentang-pengadilan-pajak",
    "topic": "general",
    "title": "UU No. 14 Tahun 2002 tentang Pengadilan Pajak",
    "citation": "UU No. 14 Tahun 2002 tentang Pengadilan Pajak",
    "focus": "Banding, gugatan, hukum acara, pembuktian, pemeriksaan persidangan, dan putusan.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Search?search=UU%2014%20Tahun%202002%20Pengadilan%20Pajak",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Dasar utama penyusunan strategi dan dokumen sengketa di Pengadilan Pajak..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Belum digantikan oleh undang-undang baru..\\nEffective period / temporal relevance: 12 April 2002.\\nDatabase note: Catat perkembangan putusan MK yang memengaruhi kelembagaan/prosedur..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-08-uu-no-12-tahun-1985-jo-uu-no-12-tahun-1994",
    "topic": "general",
    "title": "UU No. 12 Tahun 1985 jo. UU No. 12 Tahun 1994",
    "citation": "UU No. 12 Tahun 1985 jo. UU No. 12 Tahun 1994",
    "focus": "Pajak Bumi dan Bangunan yang masih relevan untuk sektor yang dikelola pemerintah pusat.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Search?search=UU%2012%20Tahun%201985%20Pajak%20Bumi%20dan%20Bangunan",
    "content": "Priority: B — Penting.\\nGroup: UU Induk.\\nPractical use: Penting untuk perkebunan, perhutanan, pertambangan, migas, dan sektor tertentu..\\nVerified status as of 20 July 2026: Berlaku sebagian sesuai pembagian kewenangan.\\nImportant relationship/amendment: PBB-P2 telah menjadi pajak daerah; PBB sektor tertentu tetap dikelola pusat..\\nEffective period / temporal relevance: Sejak 1986; perubahan 1994.\\nDatabase note: Pisahkan PBB pusat dari PBB-P2 daerah..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-09-uu-no-10-tahun-2020-tentang-bea-meterai",
    "topic": "general",
    "title": "UU No. 10 Tahun 2020 tentang Bea Meterai",
    "citation": "UU No. 10 Tahun 2020 tentang Bea Meterai",
    "focus": "Objek, tarif, saat terutang, pihak terutang, pemeteraian kemudian, dan fasilitas.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/uu-10-tahun-2020",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Dasar untuk dokumen perjanjian, alat bukti, transaksi korporasi, dan dokumen elektronik..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan UU Bea Meterai lama..\\nEffective period / temporal relevance: 1 Januari 2021.\\nDatabase note: Hubungkan dengan PP 86/2021 dan PMK 78/2024..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-10-uu-no-1-tahun-2022-tentang-hkpd",
    "topic": "general",
    "title": "UU No. 1 Tahun 2022 tentang HKPD",
    "citation": "UU No. 1 Tahun 2022 tentang HKPD",
    "focus": "Pajak daerah, retribusi daerah, opsen, dan hubungan keuangan pusat-daerah.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/uu-1-tahun-2022",
    "content": "Priority: A — Wajib.\\nGroup: UU Induk.\\nPractical use: Fondasi untuk analisis pajak provinsi/kabupaten/kota dan transaksi yang memiliki local tax exposure..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan rezim utama pajak daerah sebelumnya..\\nEffective period / temporal relevance: 5 Januari 2022; implementasi bertahap.\\nDatabase note: Database perlu memuat Perda dan Perkada per daerah..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-11-uu-no-9-tahun-2017",
    "topic": "general",
    "title": "UU No. 9 Tahun 2017",
    "citation": "UU No. 9 Tahun 2017",
    "focus": "Penetapan Perppu akses informasi keuangan untuk kepentingan perpajakan menjadi undang-undang.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://peraturan.bpk.go.id/Search?search=UU%209%20Tahun%202017%20Akses%20Informasi%20Keuangan",
    "content": "Priority: B — Penting.\\nGroup: UU Induk.\\nPractical use: Dasar AEOI/CRS dan akses DJP terhadap informasi keuangan..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Dilaksanakan lebih lanjut antara lain melalui PMK 108/2025..\\nEffective period / temporal relevance: 23 Agustus 2017.\\nDatabase note: Relevan untuk financial institutions dan high-net-worth taxpayers..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-12-pp-no-50-tahun-2022",
    "topic": "general",
    "title": "PP No. 50 Tahun 2022",
    "citation": "PP No. 50 Tahun 2022",
    "focus": "Tata cara pelaksanaan hak dan pemenuhan kewajiban perpajakan berdasarkan UU KUP.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-50-tahun-2022",
    "content": "Priority: A — Wajib.\\nGroup: PP Pelaksana.\\nPractical use: Jembatan utama antara UU KUP dan aturan teknis administrasi..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut/menggantikan sejumlah PP pelaksanaan KUP sebelumnya..\\nEffective period / temporal relevance: 12 Desember 2022.\\nDatabase note: Baca bersama PMK 81/2024 dan aturan prosedural khusus..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-13-pp-no-55-tahun-2022-jo-pp-no-20-tahun-2026",
    "topic": "general",
    "title": "PP No. 55 Tahun 2022 jo. PP No. 20 Tahun 2026",
    "citation": "PP No. 55 Tahun 2022 jo. PP No. 20 Tahun 2026",
    "focus": "Penyesuaian pengaturan di bidang PPh, termasuk natura, UMKM, anti-penghindaran, dan prinsip kewajaran.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-55-tahun-2022",
    "content": "Priority: A — Wajib.\\nGroup: PP Pelaksana.\\nPractical use: PP induk terpenting untuk PPh setelah UU HPP..\\nVerified status as of 20 July 2026: Berlaku — telah diubah.\\nImportant relationship/amendment: Perubahan terbaru melalui PP No. 20 Tahun 2026..\\nEffective period / temporal relevance: PP 55: 20 Desember 2022; perubahan: 22 April 2026.\\nDatabase note: Simpan PP 20/2026 sebagai dokumen perubahan terhubung..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-14-pp-no-44-tahun-2022",
    "topic": "vat",
    "title": "PP No. 44 Tahun 2022",
    "citation": "PP No. 44 Tahun 2022",
    "focus": "Penerapan PPN dan PPnBM secara umum.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-44-tahun-2022",
    "content": "Priority: A — Wajib.\\nGroup: PP Pelaksana.\\nPractical use: PP pelaksana utama untuk menentukan objek, saat/tempat terutang, dan mekanisme PPN..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan PP No. 1 Tahun 2012..\\nEffective period / temporal relevance: 2 Desember 2022.\\nDatabase note: Baca bersama PMK 131/2024 dan PMK 11/2025..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-15-pp-no-49-tahun-2022",
    "topic": "vat",
    "title": "PP No. 49 Tahun 2022",
    "citation": "PP No. 49 Tahun 2022",
    "focus": "PPN dibebaskan atau tidak dipungut dan PPnBM dibebaskan atas impor/penyerahan tertentu.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-49-tahun-2022",
    "content": "Priority: A — Wajib.\\nGroup: PP Pelaksana.\\nPractical use: Referensi inti untuk fasilitas PPN dan analisis recoverability pajak masukan..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mengonsolidasikan sejumlah fasilitas PPN..\\nEffective period / temporal relevance: 12 Desember 2022.\\nDatabase note: Tetap periksa PMK sektoral fasilitas..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-16-pp-no-58-tahun-2023",
    "topic": "general",
    "title": "PP No. 58 Tahun 2023",
    "citation": "PP No. 58 Tahun 2023",
    "focus": "Tarif pemotongan PPh Pasal 21 menggunakan tarif efektif rata-rata.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-58-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: PP Pelaksana.\\nPractical use: Fondasi penghitungan payroll withholding sejak 2024..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Dilaksanakan melalui PMK 168/2023..\\nEffective period / temporal relevance: 1 Januari 2024.\\nDatabase note: Gunakan tarif Pasal 17 untuk rekonsiliasi akhir tahun..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-17-pp-no-35-tahun-2023",
    "topic": "general",
    "title": "PP No. 35 Tahun 2023",
    "citation": "PP No. 35 Tahun 2023",
    "focus": "Ketentuan umum pajak daerah dan retribusi daerah.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-35-tahun-2023",
    "content": "Priority: B — Penting.\\nGroup: PP Pelaksana.\\nPractical use: Aturan pelaksana utama UU HKPD..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Harus dibaca bersama Perda dan Perkada yang relevan..\\nEffective period / temporal relevance: 16 Juni 2023.\\nDatabase note: Tarif aktual tetap ditentukan per daerah..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-18-pp-no-86-tahun-2021",
    "topic": "general",
    "title": "PP No. 86 Tahun 2021",
    "citation": "PP No. 86 Tahun 2021",
    "focus": "Pengadaan, pengelolaan, dan penjualan meterai.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pp-86-tahun-2021",
    "content": "Priority: B — Penting.\\nGroup: PP Pelaksana.\\nPractical use: Mengatur aspek operasional meterai tempel dan meterai elektronik..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan lebih lanjut dikonsolidasikan dalam PMK 78/2024..\\nEffective period / temporal relevance: 28 Oktober 2021.\\nDatabase note: Hubungkan dengan UU 10/2020..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-19-pmk-no-81-tahun-2024-jo-perubahan-terakhir-pmk-no-1-tahun-2026",
    "topic": "general",
    "title": "PMK No. 81 Tahun 2024 jo. perubahan terakhir PMK No. 1 Tahun 2026",
    "citation": "PMK No. 81 Tahun 2024 jo. perubahan terakhir PMK No. 1 Tahun 2026",
    "focus": "Ketentuan perpajakan dalam rangka pelaksanaan sistem inti administrasi perpajakan DJP.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-81-tahun-2024",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan operasional utama untuk registrasi, pembayaran, pemotongan, faktur, pelaporan, restitusi, dan layanan elektronik..\\nVerified status as of 20 July 2026: Berlaku — telah beberapa kali diubah.\\nImportant relationship/amendment: Perubahan terakhir yang dicatat: PMK No. 1 Tahun 2026..\\nEffective period / temporal relevance: 1 Januari 2025; perubahan 2026.\\nDatabase note: Status harus dipetakan sampai tingkat pasal karena banyak aturan lama dicabut sebagian..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-20-pmk-no-111-tahun-2025",
    "topic": "general",
    "title": "PMK No. 111 Tahun 2025",
    "citation": "PMK No. 111 Tahun 2025",
    "focus": "Pengawasan kepatuhan wajib pajak.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-111-tahun-2025",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Menjadi acuan penting untuk pengawasan berbasis risiko, permintaan penjelasan, dan tindak lanjut kepatuhan..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Melengkapi PMK 81/2024 dan rezim pemeriksaan..\\nEffective period / temporal relevance: 1 Januari 2026.\\nDatabase note: Penting untuk tax risk management dan respons SP2DK/pengawasan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-21-pmk-no-15-tahun-2025",
    "topic": "general",
    "title": "PMK No. 15 Tahun 2025",
    "citation": "PMK No. 15 Tahun 2025",
    "focus": "Pemeriksaan pajak dan pemeriksaan PBB.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-15-tahun-2025",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan prosedural utama untuk audit tax, hak/kewajiban pihak, jangka waktu, SPHP, dan pembahasan akhir..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan rezim PMK 17/PMK.03/2013 dan perubahannya..\\nEffective period / temporal relevance: 14 Februari 2025.\\nDatabase note: Jangan gunakan PMK 17/2013 untuk prosedur audit baru..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-22-pmk-no-118-tahun-2024",
    "topic": "general",
    "title": "PMK No. 118 Tahun 2024",
    "citation": "PMK No. 118 Tahun 2024",
    "focus": "Pembetulan, keberatan, pengurangan, penghapusan, dan pembatalan di bidang perpajakan.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-118-tahun-2024",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan utama untuk post-assessment remedies di tingkat DJP..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mengonsolidasikan dan mencabut beberapa PMK prosedural lama..\\nEffective period / temporal relevance: 1 Januari 2025.\\nDatabase note: Pisahkan pembetulan Pasal 16, keberatan, dan relief Pasal 36 KUP..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-23-pmk-no-61-tahun-2023",
    "topic": "general",
    "title": "PMK No. 61 Tahun 2023",
    "citation": "PMK No. 61 Tahun 2023",
    "focus": "Tata cara pelaksanaan penagihan pajak atas jumlah pajak yang masih harus dibayar.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-61-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan teknis penagihan aktif, Surat Paksa, sita, pencegahan, dan sandera..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan UU PPSP dan PP terkait..\\nEffective period / temporal relevance: 12 Juni 2023.\\nDatabase note: Wajib untuk dispute cash-flow dan enforcement risk..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-24-pmk-no-28-tahun-2026",
    "topic": "general",
    "title": "PMK No. 28 Tahun 2026",
    "citation": "PMK No. 28 Tahun 2026",
    "focus": "Pengembalian pendahuluan kelebihan pembayaran pajak.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-28-tahun-2026",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan terbaru untuk wajib pajak kriteria tertentu, persyaratan tertentu, dan PKP berisiko rendah..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut rezim PMK 39/PMK.03/2018 beserta perubahannya..\\nEffective period / temporal relevance: 1 Mei 2026.\\nDatabase note: Klasifikasi pemohon dan batas waktu perlu dibuat sebagai metadata..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-25-pmk-no-177-pmk-03-2022",
    "topic": "general",
    "title": "PMK No. 177/PMK.03/2022",
    "citation": "PMK No. 177/PMK.03/2022",
    "focus": "Tata cara pemeriksaan bukti permulaan tindak pidana di bidang perpajakan.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/177-pmk-03-2022",
    "content": "Priority: B — Penting.\\nGroup: Administrasi & Sengketa.\\nPractical use: Acuan utama ketika perkara bergerak dari administrasi menuju penegakan pidana pajak..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Dilaksanakan lebih teknis melalui PER-1/PJ/2024..\\nEffective period / temporal relevance: 29 Desember 2022.\\nDatabase note: Pisahkan bukper terbuka dan tertutup serta hak wajib pajak..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-26-pmk-no-17-tahun-2025",
    "topic": "general",
    "title": "PMK No. 17 Tahun 2025",
    "citation": "PMK No. 17 Tahun 2025",
    "focus": "Penyidikan tindak pidana di bidang perpajakan.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-17-tahun-2025",
    "content": "Priority: B — Penting.\\nGroup: Administrasi & Sengketa.\\nPractical use: Kerangka prosedural untuk penyidikan, penghentian, dan koordinasi penegakan hukum pajak..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Memperbarui aturan teknis penyidikan pajak..\\nEffective period / temporal relevance: 25 Februari 2025.\\nDatabase note: Relevan untuk tax controversy berisiko tinggi..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-27-pmk-no-44-tahun-2026",
    "topic": "general",
    "title": "PMK No. 44 Tahun 2026",
    "citation": "PMK No. 44 Tahun 2026",
    "focus": "Persyaratan menjadi kuasa di bidang perpajakan dan pelaksanaan hak/kewajiban kuasa.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-44-tahun-2026",
    "content": "Priority: A — Wajib.\\nGroup: Administrasi & Sengketa.\\nPractical use: Aturan terbaru untuk representation di hadapan DJP..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut PMK 229/PMK.03/2014..\\nEffective period / temporal relevance: 6 Juli 2026.\\nDatabase note: Pisahkan kuasa konsultan, pegawai, keluarga, dan pihak lain yang diizinkan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-28-pmk-no-108-tahun-2025",
    "topic": "general",
    "title": "PMK No. 108 Tahun 2025",
    "citation": "PMK No. 108 Tahun 2025",
    "focus": "Petunjuk teknis akses informasi keuangan untuk kepentingan perpajakan.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-108-tahun-2025",
    "content": "Priority: B — Penting.\\nGroup: Administrasi & Sengketa.\\nPractical use: Acuan terbaru AEOI/CRS dan kewajiban lembaga keuangan pelapor..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut PMK 70/PMK.03/2017 beserta perubahannya..\\nEffective period / temporal relevance: 1 Januari 2026.\\nDatabase note: Sangat penting untuk perbankan, kustodian, asuransi, dan investasi..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-29-pmk-no-168-tahun-2023",
    "topic": "general",
    "title": "PMK No. 168 Tahun 2023",
    "citation": "PMK No. 168 Tahun 2023",
    "focus": "Petunjuk pelaksanaan pemotongan PPh atas penghasilan sehubungan dengan pekerjaan, jasa, atau kegiatan orang pribadi.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-168-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Aturan teknis utama PPh Pasal 21 dan Pasal 26 orang pribadi..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Melaksanakan PP 58/2023..\\nEffective period / temporal relevance: 1 Januari 2024.\\nDatabase note: Mencakup pegawai tetap/tidak tetap, bukan pegawai, dan peserta kegiatan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-30-pmk-no-66-tahun-2023",
    "topic": "general",
    "title": "PMK No. 66 Tahun 2023",
    "citation": "PMK No. 66 Tahun 2023",
    "focus": "Perlakuan PPh atas penggantian atau imbalan dalam bentuk natura dan/atau kenikmatan.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-66-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Menentukan deductibility pemberi dan taxability penerima atas employee benefits/natura..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan PP 55/2022..\\nEffective period / temporal relevance: 1 Juli 2023.\\nDatabase note: Periksa daftar pengecualian dan metode penilaian..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-31-pmk-no-72-tahun-2023",
    "topic": "general",
    "title": "PMK No. 72 Tahun 2023",
    "citation": "PMK No. 72 Tahun 2023",
    "focus": "Penyusutan harta berwujud dan amortisasi harta tak berwujud.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-72-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Referensi utama rekonsiliasi fiskal aset tetap dan intangible..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mengonsolidasikan aturan kelompok aset dan masa manfaat..\\nEffective period / temporal relevance: 17 Juli 2023.\\nDatabase note: Termasuk mekanisme pemberitahuan masa manfaat lebih panjang..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-32-pmk-no-79-tahun-2023",
    "topic": "general",
    "title": "PMK No. 79 Tahun 2023",
    "citation": "PMK No. 79 Tahun 2023",
    "focus": "Tata cara penilaian untuk tujuan perpajakan.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-79-tahun-2023",
    "content": "Priority: B — Penting.\\nGroup: PPh.\\nPractical use: Penting untuk transaksi aset, restrukturisasi, transfer bisnis, dan pengujian nilai wajar..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Melengkapi kewenangan penilaian DJP..\\nEffective period / temporal relevance: 24 Agustus 2023.\\nDatabase note: Hubungkan dengan transfer pricing dan transaksi afiliasi..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-33-pmk-no-164-tahun-2023",
    "topic": "general",
    "title": "PMK No. 164 Tahun 2023",
    "citation": "PMK No. 164 Tahun 2023",
    "focus": "Tata cara pengenaan PPh atas usaha dengan peredaran bruto tertentu dan kewajiban administrasi terkait.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-164-tahun-2023",
    "content": "Priority: B — Penting.\\nGroup: PPh.\\nPractical use: Aturan utama PPh final UMKM serta pernyataan penggunaan tarif umum..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Melaksanakan PP 55/2022..\\nEffective period / temporal relevance: 29 Desember 2023.\\nDatabase note: Periksa jangka waktu fasilitas per jenis wajib pajak..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-34-pmk-no-51-tahun-2025",
    "topic": "general",
    "title": "PMK No. 51 Tahun 2025",
    "citation": "PMK No. 51 Tahun 2025",
    "focus": "Pemungutan PPh Pasal 22 sehubungan dengan pembayaran dan kegiatan tertentu.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-51-tahun-2025",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Aturan PPh Pasal 22 terbaru untuk badan pemungut, impor, dan transaksi tertentu..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan/mengonsolidasikan ketentuan PPh Pasal 22 terdahulu..\\nEffective period / temporal relevance: 1 Agustus 2025.\\nDatabase note: Gunakan untuk transaksi sejak tanggal efektif..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-35-pmk-no-141-pmk-03-2015",
    "topic": "general",
    "title": "PMK No. 141/PMK.03/2015",
    "citation": "PMK No. 141/PMK.03/2015",
    "focus": "Jenis jasa lain yang dipotong PPh Pasal 23.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/141-pmk-03-2015",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Daftar operasional utama untuk menentukan pemotongan PPh Pasal 23 atas jasa..\\nVerified status as of 20 July 2026: Berlaku sepanjang belum diubah/dicabut.\\nImportant relationship/amendment: Administrasi pemotongan/pelaporan kini juga terkait PMK 81/2024..\\nEffective period / temporal relevance: 24 Agustus 2015.\\nDatabase note: Lakukan status check saat ada revisi daftar jasa..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-36-pmk-no-169-pmk-010-2015",
    "topic": "general",
    "title": "PMK No. 169/PMK.010/2015",
    "citation": "PMK No. 169/PMK.010/2015",
    "focus": "Perbandingan utang dan modal perusahaan untuk keperluan penghitungan PPh.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/169-pmk-010-2015",
    "content": "Priority: A — Wajib.\\nGroup: PPh.\\nPractical use: Dasar thin capitalization domestik dan batas DER..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Harus dibaca bersama Pasal 18 UU PPh dan aturan transfer pricing pembiayaan..\\nEffective period / temporal relevance: 9 September 2015.\\nDatabase note: Periksa pengecualian sektor dan kewajiban pelaporan utang swasta luar negeri..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-37-pmk-no-172-tahun-2023",
    "topic": "transfer_pricing",
    "title": "PMK No. 172 Tahun 2023",
    "citation": "PMK No. 172 Tahun 2023",
    "focus": "Penerapan prinsip kewajaran dan kelaziman usaha, dokumentasi TP, pemeriksaan TP, corresponding adjustment, APA, dan MAP.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-172-tahun-2023",
    "content": "Priority: A — Wajib.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Regulasi inti transfer pricing Indonesia..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut PMK 213/2016, PMK 49/2019, dan PMK 22/2020..\\nEffective period / temporal relevance: 29 Desember 2023.\\nDatabase note: Metadata sebaiknya dipisah: PKKU, TP Doc, APA, MAP, corresponding adjustment..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-38-pmk-no-112-tahun-2025",
    "topic": "transfer_pricing",
    "title": "PMK No. 112 Tahun 2025",
    "citation": "PMK No. 112 Tahun 2025",
    "focus": "Tata cara penerapan Persetujuan Penghindaran Pajak Berganda.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-112-tahun-2025",
    "content": "Priority: A — Wajib.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Aturan utama treaty relief, Form DGT, beneficial ownership, dan anti-abuse administratif..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Menggantikan rezim administratif P3B sebelumnya..\\nEffective period / temporal relevance: Tahun 2025 sesuai ketentuan efektif.\\nDatabase note: Bedakan syarat substantif treaty dari syarat administratif domestik..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-39-pmk-no-35-pmk-03-2019",
    "topic": "transfer_pricing",
    "title": "PMK No. 35/PMK.03/2019",
    "citation": "PMK No. 35/PMK.03/2019",
    "focus": "Penentuan bentuk usaha tetap.",
    "relevance": 84,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/35-pmk-03-2019",
    "content": "Priority: B — Penting.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Referensi domestik utama untuk fixed place, construction, service, agent, dan insurance PE..\\nVerified status as of 20 July 2026: Berlaku sepanjang belum diubah/dicabut.\\nImportant relationship/amendment: Harus dibaca bersama P3B yang relevan..\\nEffective period / temporal relevance: 1 April 2019.\\nDatabase note: Treaty dapat membatasi hak pemajakan domestik..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-40-pmk-no-192-pmk-03-2018",
    "topic": "transfer_pricing",
    "title": "PMK No. 192/PMK.03/2018",
    "citation": "PMK No. 192/PMK.03/2018",
    "focus": "Pelaksanaan pengkreditan pajak atas penghasilan dari luar negeri.",
    "relevance": 84,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/192-pmk-03-2018",
    "content": "Priority: B — Penting.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Aturan utama foreign tax credit dan penghindaran pajak berganda secara unilateral..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Harus dibaca bersama Pasal 24 UU PPh dan P3B..\\nEffective period / temporal relevance: 31 Desember 2018.\\nDatabase note: Periksa per-country limitation dan timing pengkreditan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-41-pmk-no-107-pmk-03-2017-jo-pmk-no-93-pmk-03-2019",
    "topic": "transfer_pricing",
    "title": "PMK No. 107/PMK.03/2017 jo. PMK No. 93/PMK.03/2019",
    "citation": "PMK No. 107/PMK.03/2017 jo. PMK No. 93/PMK.03/2019",
    "focus": "Penetapan saat diperolehnya dividen dan dasar penghitungan deemed dividend atas penyertaan pada badan usaha luar negeri nonbursa.",
    "relevance": 84,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/107-pmk-03-2017",
    "content": "Priority: B — Penting.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Aturan CFC Indonesia..\\nVerified status as of 20 July 2026: Berlaku — telah diubah.\\nImportant relationship/amendment: Diubah oleh PMK No. 93/PMK.03/2019..\\nEffective period / temporal relevance: 2017; perubahan 2019.\\nDatabase note: Periksa pengecualian active income dan mekanisme kredit/penghasilan aktual..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-42-pmk-no-136-tahun-2024",
    "topic": "transfer_pricing",
    "title": "PMK No. 136 Tahun 2024",
    "citation": "PMK No. 136 Tahun 2024",
    "focus": "Pengenaan pajak minimum global berdasarkan ketentuan GloBE.",
    "relevance": 84,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-136-tahun-2024",
    "content": "Priority: B — Penting.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Aturan Indonesia untuk IIR, UTPR, dan QDMTT bagi grup multinasional dalam cakupan..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan Pilar Dua di Indonesia..\\nEffective period / temporal relevance: Tahun pajak 2025 dan seterusnya sesuai ketentuan.\\nDatabase note: Simpan OECD Administrative Guidance sebagai guidance, bukan peraturan domestik..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-43-p3b-indonesia-protokol-dan-mli",
    "topic": "transfer_pricing",
    "title": "P3B Indonesia, Protokol, dan MLI",
    "citation": "P3B Indonesia, Protokol, dan MLI",
    "focus": "Jaringan tax treaty Indonesia, protokol perubahan, serta modifikasi oleh Multilateral Instrument.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://www.pajak.go.id/id/tax-treaty",
    "content": "Priority: A — Wajib.\\nGroup: Transfer Pricing & Internasional.\\nPractical use: Menentukan hak pemajakan, tarif treaty, PE, MAP, dan eliminasi pajak berganda..\\nVerified status as of 20 July 2026: Berlaku per negara dan instrumen.\\nImportant relationship/amendment: Setiap treaty harus dicatat sebagai dokumen terpisah dengan effective date dan MLI position..\\nEffective period / temporal relevance: Berbeda per negara/tahun pajak.\\nDatabase note: Jangan mengandalkan satu teks generik; gunakan treaty dan synthesized text yang relevan..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-44-pmk-no-131-tahun-2024",
    "topic": "vat",
    "title": "PMK No. 131 Tahun 2024",
    "citation": "PMK No. 131 Tahun 2024",
    "focus": "Perlakuan PPN atas impor, penyerahan, serta pemanfaatan BKP tidak berwujud dan JKP dari luar daerah pabean.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-131-tahun-2024",
    "content": "Priority: A — Wajib.\\nGroup: PPN.\\nPractical use: Aturan teknis utama mekanisme PPN sejak perubahan 2025..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Harus dibaca bersama UU PPN dan PP 44/2022..\\nEffective period / temporal relevance: 1 Januari 2025.\\nDatabase note: Periksa formula DPP dan perlakuan barang mewah/nonmewah..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-45-pmk-no-11-tahun-2025-jo-pmk-no-53-tahun-2025",
    "topic": "vat",
    "title": "PMK No. 11 Tahun 2025 jo. PMK No. 53 Tahun 2025",
    "citation": "PMK No. 11 Tahun 2025 jo. PMK No. 53 Tahun 2025",
    "focus": "Nilai lain sebagai dasar pengenaan pajak dan besaran tertentu PPN.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-11-tahun-2025",
    "content": "Priority: A — Wajib.\\nGroup: PPN.\\nPractical use: Referensi utama untuk transaksi dengan DPP nilai lain atau PPN besaran tertentu..\\nVerified status as of 20 July 2026: Berlaku — telah diubah.\\nImportant relationship/amendment: Diubah oleh PMK No. 53 Tahun 2025..\\nEffective period / temporal relevance: 4 Februari 2025; perubahan 2025.\\nDatabase note: Buat tag per jenis transaksi agar mudah dicari..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-46-pmk-no-78-tahun-2024",
    "topic": "general",
    "title": "PMK No. 78 Tahun 2024",
    "citation": "PMK No. 78 Tahun 2024",
    "focus": "Ketentuan pelaksanaan Bea Meterai.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-78-tahun-2024",
    "content": "Priority: A — Wajib.\\nGroup: Bea Meterai.\\nPractical use: Aturan teknis terintegrasi untuk meterai tempel, elektronik, pemeteraian kemudian, dan pemungut..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Mencabut/mengonsolidasikan beberapa PMK Bea Meterai tahun 2021..\\nEffective period / temporal relevance: 1 November 2024.\\nDatabase note: Gunakan bersama UU 10/2020 dan PP 86/2021..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-47-pmk-no-37-tahun-2025",
    "topic": "general",
    "title": "PMK No. 37 Tahun 2025",
    "citation": "PMK No. 37 Tahun 2025",
    "focus": "Penunjukan pihak lain sebagai pemungut PPh dan tata cara pemungutan, penyetoran, dan pelaporan atas pedagang dalam sistem elektronik.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-37-tahun-2025",
    "content": "Priority: B — Penting.\\nGroup: Ekonomi Digital.\\nPractical use: Penting untuk marketplace dan merchant yang bertransaksi melalui platform..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Membentuk rezim pemungutan PPh oleh platform tertentu..\\nEffective period / temporal relevance: Tahun 2025 sesuai ketentuan efektif.\\nDatabase note: Relevansi bergantung model platform dan penunjukan DJP..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-48-pmk-no-50-tahun-2025",
    "topic": "vat",
    "title": "PMK No. 50 Tahun 2025",
    "citation": "PMK No. 50 Tahun 2025",
    "focus": "Perlakuan PPN dan PPh atas transaksi perdagangan aset kripto.",
    "relevance": 84,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/pmk-50-tahun-2025",
    "content": "Priority: B — Penting.\\nGroup: Ekonomi Digital.\\nPractical use: Regulasi inti untuk exchange, trader, miner, dan penyedia jasa terkait aset kripto..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Memperbarui rezim pajak aset kripto..\\nEffective period / temporal relevance: 1 Agustus 2025.\\nDatabase note: Periksa klasifikasi aset dan status penyelenggara..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-49-per-7-pj-2025",
    "topic": "general",
    "title": "PER-7/PJ/2025",
    "citation": "PER-7/PJ/2025",
    "focus": "Administrasi NPWP, PKP, objek PBB, dan saluran pelayanan pada sistem inti administrasi perpajakan DJP.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/per-7pj2025",
    "content": "Priority: A — Wajib.\\nGroup: PER DJP.\\nPractical use: Aturan operasional registrasi dan perubahan data wajib pajak..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan PMK 81/2024..\\nEffective period / temporal relevance: 2025.\\nDatabase note: Penting untuk onboarding, deregistration, dan PKP..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-50-per-8-pj-2025",
    "topic": "general",
    "title": "PER-8/PJ/2025",
    "citation": "PER-8/PJ/2025",
    "focus": "Pemberian layanan administrasi perpajakan tertentu melalui sistem inti administrasi perpajakan DJP.",
    "relevance": 92,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/per-8pj2025",
    "content": "Priority: A — Wajib.\\nGroup: PER DJP.\\nPractical use: Panduan operasional berbagai permohonan dan layanan administrasi..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan PMK 81/2024..\\nEffective period / temporal relevance: 2025.\\nDatabase note: Gunakan indeks layanan untuk navigasi database..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-51-per-11-pj-2025-jo-per-3-pj-2026",
    "topic": "vat",
    "title": "PER-11/PJ/2025 jo. PER-3/PJ/2026",
    "citation": "PER-11/PJ/2025 jo. PER-3/PJ/2026",
    "focus": "Ketentuan pelaporan PPh, PPN, PPnBM, dan Bea Meterai dalam sistem inti administrasi perpajakan DJP.",
    "relevance": 96,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/per-11pj2025",
    "content": "Priority: A — Wajib.\\nGroup: PER DJP.\\nPractical use: Aturan operasional utama SPT Masa/Tahunan, bukti potong, dan pelaporan elektronik..\\nVerified status as of 20 July 2026: Berlaku — telah diubah sebagian.\\nImportant relationship/amendment: PER-3/PJ/2026 mengubah/mencabut sebagian ketentuan PER-11/PJ/2025..\\nEffective period / temporal relevance: 2025; perubahan 2026.\\nDatabase note: Status harus dipetakan sampai tingkat pasal/lampiran..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-52-per-10-pj-2025",
    "topic": "general",
    "title": "PER-10/PJ/2025",
    "citation": "PER-10/PJ/2025",
    "focus": "Pelaksanaan pertukaran informasi berdasarkan perjanjian internasional.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/per-10pj2025",
    "content": "Priority: B — Penting.\\nGroup: PER DJP.\\nPractical use: Aturan teknis EOI, AEOI, dan pertukaran informasi atas permintaan/spontan..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Melaksanakan perjanjian internasional dan PMK akses informasi..\\nEffective period / temporal relevance: 2025.\\nDatabase note: Penting untuk tax transparency dan cross-border controversy..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  },
  {
    "id": "essential-53-per-1-pj-2024",
    "topic": "general",
    "title": "PER-1/PJ/2024",
    "citation": "PER-1/PJ/2024",
    "focus": "Petunjuk pelaksanaan pemeriksaan bukti permulaan tindak pidana perpajakan.",
    "relevance": 80,
    "source": "seed",
    "sourceUrl": "https://jdih.kemenkeu.go.id/dok/per-1pj2024",
    "content": "Priority: B — Penting.\\nGroup: PER DJP.\\nPractical use: Aturan teknis untuk pelaksanaan bukper oleh DJP..\\nVerified status as of 20 July 2026: Berlaku.\\nImportant relationship/amendment: Pelaksanaan PMK 177/PMK.03/2022..\\nEffective period / temporal relevance: 2024.\\nDatabase note: Gunakan bersama ketentuan KUP dan PMK 177/2022..\\nSource provenance: curated essential-tax-regulation registry; official source URL should be checked before relying on the rule as current law."
  }
];
